# HTTP Server
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#Server info
info:
  app:
    name: ${spring.application.name}
    description: Info SAS API
    groupId: com.torresj
    artifactId: infosas-telegram-bot
    version: ${APP_VERSION:SNAPSHOT}
