apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infosas-telegram-bot.fullname" . }}
  labels:
    {{- include "infosas-telegram-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "infosas-telegram-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "infosas-telegram-bot.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets: 
        - name: {{ .Values.imagePullSecrets }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /infosas-telegram-bot/logs
              name: infosas-telegram-bot-logs
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 3
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.version }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: BOT_NAME
              value: "{{ .Values.telegram.bot.name }}"
            - name: BOT_TOKEN
              value: "{{ .Values.telegram.bot.token }}"
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmq.host }}"
            - name: RABBITMQ_PORT
              value: "{{ .Values.rabbitmq.port }}"
            - name: RABBITMQ_USER
              value: "{{ .Values.rabbitmq.username }}"
            - name: RABBITMQ_PASSWORD
              value: "{{ .Values.rabbitmq.password }}"
            {{ if .Values.cloud.config.enabled -}}
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URL
              value: "https://{{ .Values.cloud.config.username }}:{{ .Values.cloud.config.password }}@{{ .Values.cloud.config.url }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: infosas-telegram-bot-logs
          persistentVolumeClaim:
            claimName: infosas-telegram-bot-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
