apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infosas-telegram-bot-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
